[tool.poetry]
name = "repair-tools"
version = "0.1.0"
description = ""
authors = ["Emilee Buytkins <emileebuytkins@nypl.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
requests = "^2.32.4"
pymediainfo = "^7.0.1"
msgpack = "^1.1.1"
tqdm = "^4.67.1"
boto3 = "^1.40.42"
pandas = "^2.3.3"
colorama = "^0.4.6"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
pytest-mock = "^3.14.1"
setuptools = "^80.1.0"

[tool.poetry.scripts]
delete_hidden_files = 'repair_tools.delete_hidden_files:main'
correct_double_bag = 'repair_tools.correct_double_bag:main'
compare_sources = 'repair_tools.compare_sources:main'
prsv_move = 'repair_tools.prsv_move:main'
move_reingest = 'repair_tools.move_reingest:main'
download_sc_mp4 = 'repair_tools.download_sc_mp4:main'
create_manifest = 'repair_tools.create_manifest:main'
create_bag_structure = 'repair_tools.create_bag_structure:main'
create_symlink = 'repair_tools.path_tools.create_symlink:main'
directory_indexer = 'repair_tools.path_tools.directory_indexer:main'
search_index = 'repair_tools.path_tools.search_index:main'
export_workflows = 'repair_tools.export_workflows:main'
mix_streams = 'repair_tools.mix_streams:main'
check_size = 'repair_tools.check_size:main'
clear_transient_folders = 'repair_tools.clear_transient_folders:main'
find_duplicates = 'repair_tools.find_duplicates:main'
delete_0byte = 'repair_tools.delete_0byte:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

